### ISSUE TITLE
Access glottolog data from github repos fork

### ISSUE THREAD

**Issue by xrotwang** [OneAdder/lingtypology#1] opened 2019-02-14 10:17 UTC
Hi there, just came across this repos and I think what I noted for the R repos applies here as well:
https://github.com/ropensci/lingtypology/issues/1

Basically,whenever you provide access to glottolog data through your tools, you should
- either state explicitly and visibly which version of glottolog data you are using
- or (recommended) give users control over which version of glottolog data they want to use your tools with.

Let me know if I can help with anything!

**Comment by OneAdder** [comment] 2019-02-14 16:48
Hi,
I'm glad to see you here!
Sorry for the late response. I started this project about a week ago and I didn't expect any issues yet and didn't notice this one.
I already saw your issue in agricolamz's repo and I thought that using one static table is not the most exciting idea. If I understand it correctly, I can use pyglottolog and if I install and update it with pip I will get the most recent version of glottolog data. Am I correct?
And by the way, if there is no documentation for pyglottolog, could you help me with how to do some particular things with it?

**Comment by OneAdder** [comment] 2019-02-14 17:40
Well, pyglottolog doesn't download the data.
Is it acceptable if my package will use some version by default and there will be a script that downloads the latest version and modifies the table?

**Comment by xrotwang** [comment] 2019-02-14 19:45
Yes, installing pyglottolog is not going to download any data. So I think the best approach might be as follows:
- `lingtypology` should come with a small script/command line tool, which uses pyglottolog to aggregate the data from `clld/glottolog` into the particular format `lingtypology` needs.
- this tool can also be used to create data based on the latest glottolog release for distribution with a packaged version of `lingtypology`.
- users who want to use `lingtypology` with a different version of glottolog data can obtain a clone or export of this data and run the tool locally.

I'll try to put a PR together implementing such a tool for `lingtypology`.

**Comment by OneAdder** [comment] 2019-02-14 20:18
I agree, it seems to be the best way.
I use this table for now: [glottolog.original.tsv](https://github.com/ropensci/lingtypology/blob/master/database_creation/glottolog.original.tsv)
As far as I understand it was created using `pyglottolog`. If it is so, could you share it?

**Comment by agricolamz** [comment] 2019-02-15 04:26
No, it is not. But if somebody will write this script, I will be happy to use it! I'm still using the old version of the database that I've created [in this script](https://github.com/ropensci/lingtypology/blob/master/database_creation/glottolog_database_creation.R). All changes in glottolog I've done are listed from line number 154

**Comment by xrotwang** [comment] 2019-02-15 07:43
ok, I'll write a [recipe for the Glottolog cookbook](https://github.com/clld/glottolog/tree/master/cookbook) describing how to create this CSV file using `pyglottolog`. Then we can think about how to integrate this into your tools.

**Comment by xrotwang** [comment] 2019-02-15 09:01
Looking at `glottolog.original.tsv`, it seems not all of the data comes from Glottolog, and for some columns, I'd prefer changing the values. E.g. `affiliation` should not list sub-group **names** but rather Glottocodes, which can be resolved to complete languoid info using the respective row of the table.

So here's a proposal: The [D-PLACE](https://d-place.org) database also includes data from Glottolog. This data is integrated much like we discussed here:
- Some [python code](https://github.com/D-PLACE/pydplace/blob/e7f9bf4a800f8e868be0f5729ee7dade1f06d440/src/pydplace/glottolog.py#L134-L158) loops over the Glottolog languoids using [pyglottolog](https://github.com/clld/pyglottolog/blob/fa5c83dc3832dfe685fa496ea575f5ed229dd2ca/src/pyglottolog/api.py#L89) to access a local `clld/glottolog` clone or export ...
- ... creating a [CSV file](https://github.com/D-PLACE/dplace-data/blob/master/csv/glottolog.csv) with the extracted data.

If you could work from this file instead, I'd be willing to add the code to create it into `pyglottolog`, thus giving you a simple command `glottolog --repos=PATH/TO/clld/glottolog languoids` (or similar) which you could use to recreate the data dump.

**Comment by xrotwang** [comment] 2019-02-15 09:06
I'd also add `latitude`, `longitude`. Anything else? `countries` may blow up the file size quite a bit, but could be added as well.

**Comment by xrotwang** [comment] 2019-02-15 09:18
Oh, and while we're at this topic: Maybe this aggregated languoids CSV file should be a valid [CLDF LanguageTable](https://github.com/cldf/cldf/tree/master/components/languages) - which basically means a couple of columns would have different names?

**Comment by OneAdder** [comment] 2019-02-15 09:32
I'm not sure about George but for my idea I need `id`, `name`, `affiliation`, `latitude`, `longitude`. If I have something that have these columns I can easily work with it. I also think that using Glottolog IDs in the `affiliation` column is better.
So, I think that your proposal about D-Place is a great idea. It will be very helpful if you add this code.

**Comment by xrotwang** [comment] 2019-02-15 12:13
@OneAdder @agricolamz just released pyglottolog 1.4 with support for creating a CSV extract of languoid data, see https://github.com/clld/pyglottolog#extracting-languoid-data
Let me know whether this fits the bill.

**Comment by OneAdder** [comment] 2019-02-15 14:05
Thank you for your support. I made a couple of commits just now and `lingtypology` now uses the CSV extract of version `1.2.1-138-g229faafceb.`
I will implement the tool that will allow to download the most recent version when `lingtypology` will be ready for a release. Until then I'll keep the issue open.
Is it acceptable?

**Comment by xrotwang** [comment] 2019-02-15 14:13
Yes, perfect. Do you need help with turning lingtypology into a proper
python package?

Am Fr., 15. Feb. 2019, 15:05 hat OneAdder <notifications@github.com>
geschrieben:

**Comment by OneAdder** [comment] 2019-02-15 21:13
It's not ready yet to be turned into a proper package. There are still some functions that I need to implement and I want to make a documentation or at least a quick start guide.
Thank you for your help!

**Comment by OneAdder** [comment] 2019-05-01 21:28
Hi, @xrotwang , I packaged my library and made a function that downloads the newest version of Glottolog. It's a bit buggy, it confuses `pip` and works only under Linux and macOS. I figured out that this way is stupid and I will just make it use local data instead of copying the new table to the installation directory...
I will do so, write a howto for my package and upload it to PyPI.
BTW, I will download the newest glottolog version and include it into the package with each new release.
I close the issue?

**Comment by xrotwang** [comment] 2019-05-02 07:08
@OneAdder are you ok with me having a look at the code to update the Glottolog data?

**Comment by xrotwang** [comment] 2019-05-02 08:03
I agree that copying data into the installation dir of a package is not a good idea. So yes, letting users choose a local copy of the glottolog data would be the best idea. I also saw that your `download_glottolog` function assumes the user has `git` installed. I'd say with this assumption it would be simpler to just require the user to do the cloning/updating of `clld/glottolog` out of band, i.e. before using your package.

Note also that the remainder of your `update_data` function should also work with an unpacked download of a [released version](https://github.com/clld/glottolog/releases), i.e. would also be available to users not having `git` installed.

So by letting users specify a local export or clone of `clld/glottolog` rather than requiring `git` to be installed, you could
- shave off a couple of lines of somewhat limited functionality from your package
- broaden the potential user base (by not requiring `git` or linux or macOS)

**Comment by OneAdder** [comment] 2019-05-02 09:02
The problem is that forcing the user to download >700 MiB of data is a bit too cruel :)  
I think I'll make it so:
1) Make user download it himself (with `git` or just a release version).
2) Make an entry_point so that user can update the data and store it locally.
3) In `__init__.py` I will check whether user wants to use the default data or the one that the entry_point script generated.

For now I will mark it as prerelease and upload it to PyPI. Updating Glottolog is not really the main feature. Is it okay?

**Comment by xrotwang** [comment] 2019-05-02 09:42
Yes, go ahead. Is it ok if I send a pull request at some point, adding tests, etc.?

**Comment by xrotwang** [comment] 2019-05-02 09:47
I guess what I would do about initializing the glottolog data in a costumizable way is:
1. Make the initialized Pandas dataframe a private attribute `lingtypology.glottolog._glottolog`.
2. Add a `def init(data=None)` function to `lingtypology.glottolog`, which accepts an argument `data` as follows:
   - If `data is None`: Use the glottolog data distributed with the package.
   - If `data` is the path to a csv file: Assume this file has been created running `glottolog languoids` and read into dataframe.
   - If `data` is the path to a directory: Assume this directory is a clone or export of `clld/glottolog`, run `glottolog languoids` on it and read the resulting csv file.

This seems flexible as well as fairly transparent to me.

**Comment by OneAdder** [comment] 2019-05-02 10:03
Thank you, I probably will make it so in the future. For now I just made glottolog.py check whether something is under `~/.lingtypology_data`. I will add an instruction how to download the Glottolog data and use pyglottolog.

**Comment by OneAdder** [comment] 2019-05-02 10:04
About tests. I was thinking to turn my examples.py to tests

**Comment by xrotwang** [comment] 2019-05-02 10:08
Yes, turning the examples into tests would have been my first idea, too. Do you have experience with using `pytest`?

**Comment by OneAdder** [comment] 2019-05-02 10:21
No, but I think of using [this](https://python-packaging.readthedocs.io/en/latest/testing.html). Is it a good way?

**Comment by xrotwang** [comment] 2019-05-02 10:26
I'd say the python community has mostly move to pytest. If you don't mind, I can put together a PR, wiring the package up with pytest for testing.

**Comment by OneAdder** [comment] 2019-05-02 10:29
That would be most helpful!

**Comment by xrotwang** [comment] 2019-05-02 11:11
voila: https://github.com/OneAdder/lingtypology/pull/2

**Closed as completed** 2019-05-02 14:04 UTC
